name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: npm install

    - run: npm run build --prefix-paths

    - name: Publish
      if: github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./public
        publish_branch: gh-pages
        deploy_key: ${{ secrets.PAGES_DEPLOY_KEY }}
